define
legend sub entity,
    owns legend_id @key,
    owns legend_description,
    owns legend_query,
    owns legend_query_options;

legend_id sub attribute, value string;
legend_description sub attribute, value string;
legend_query sub attribute, value string;
legend_query_options sub attribute, value string;
