define
man sub entity, owns name, owns age, owns birth, owns citizen;
name sub attribute, value string;
age sub attribute, value long;
birth sub attribute, value datetime;
citizen sub attribute, value boolean;

insert
$b isa man,
    has name "Brandon",
    has age 99,
    has birth 2020-02-02,
    has citizen true;
$r isa man,
    has name "Ryan",
    has age 98,
    has birth 2010-01-01,
    has citizen false;

match
$m isa man, has name $n, has age $a, has birth $b, has citizen $c;
$c = true;