define
name sub attribute, value string;
state sub entity, owns name,
    plays location:located, plays location:locating;
city sub entity, owns name,
    plays location:located, plays location:locating;
country sub entity, owns name,
    plays location:located, plays location:locating;

location sub relation,
    relates located,
    relates locating;

rule transitive-location:
when {
  (located: $x, locating: $y) isa location;
  (located: $y, locating: $z) isa location;
} then {
  (located: $x, locating: $z) isa location; #todo: shouldn't need 'isa location' but tests will fail
};

insert
$ci isa city, has name "Tampa";
$s isa state, has name "Florida";
$co isa country, has name "USA";
(located: $ci, locating: $s) isa location;
(located: $s, locating: $co) isa location;

match
$c isa city, has name $cn;
$co isa country, has name $con;
($c, $co);